config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  resources :home

  # You can have the root of your site routed with "root"
  root 'home#index'

 	namespace :api do
	  namespace :v1 do
	    resources :posts
	  end
	end 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	
	validates :username, uniqueness: true
	validate :username_in_one_word
	validates :username, :format => { with: /\A[a-zA-Z0-9]*\z/ , :message => 'no special characters, only letters and numbers' }
	has_many :posts
	before_create do |doc|
	  doc.api_key = doc.generate_api_key
	end

  attr_accessor :login
  def self.find_for_database_authentication warden_conditions
	  conditions = warden_conditions.dup
	  login = conditions.delete(:login)
	  where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
	end

	protected

	# Attempt to find a user by it's email. If a record is found, send new
	# password instructions to it. If not user is found, returns a new user
	# with an email not found error.
	def self.send_reset_password_instructions attributes = {}
	  recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
	  recoverable.send_reset_password_instructions if recoverable.persisted?
	  recoverable
	end

	def self.find_recoverable_or_initialize_with_errors required_attributes, attributes, error = :invalid
	  (case_insensitive_keys || []).each {|k| attributes[k].try(:downcase!)}

	  attributes = attributes.slice(*required_attributes)
	  attributes.delete_if {|_key, value| value.blank?}

	  if attributes.size == required_attributes.size
	    if attributes.key?(:login)
	      login = attributes.delete(:login)
	      record = find_record(login)
	    else
	      record = where(attributes).first
	    end
	  end

	  unless record
	    record = new

	    required_attributes.each do |key|
	      value = attributes[key]
	      record.send("#{key}=", value)
	      record.errors.add(key, value.present? ? error : :blank)
	    end
	  end
	  record
	end

	def self.find_record login
	  where(["username = :value OR email = :value", {value: login}]).first
	end

	def generate_api_key
	  loop do
	    token = SecureRandom.base64.tr('+/=', 'Qrt')
	    break token unless User.exists?(api_key: token)
	  end
	end

	private

	def username_in_one_word
	  if username.to_s.squish.split.size != 1
	    errors.add(:username, 'must be one word')
	  end
	end

	
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
	def authenticate
	  api_key = request.headers['X-Api-Key']
	  @user = User.where(api_key: api_key).first if api_key
	 
	  unless @user
	    head status: :unauthorized
	    return false
	  end
	end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::ApiController
	respond_to :json
  before_action :authenticate
 
  def index
    @posts = @user.posts.all
    @response = {:user=> @user, :posts=>@posts}
    respond_with @response
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.posts.order("post_name").page(params[:page]).per(5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # Update & Destroy is not needed as per requirement 

  # # PATCH/PUT /posts/1
  # # PATCH/PUT /posts/1.json
  # def update
  #   respond_to do |format|
  #     if @post.update(post_params)
  #       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /posts/1
  # # DELETE /posts/1.json
  # def destroy
  #   @post.destroy
  #   respond_to do |format|
  #     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update] # probably want to keep using this

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # # GET /users/1
  # # GET /users/1.json
  def show

  end

  # GET /users/1/edit
  def edit

  end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role, :user_name)
    end

end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_name
		"#{current_user.first_name} #{current_user.last_name}"
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Simple Sign Up & Sign In Website</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %><br/>
  <%= link_to "New Post", new_post_path, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suventure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_name %><br>
    <%= f.text_field :post_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%#= notice %></p>
<%= paginate @posts %>
<h1>Listing Posts of <%= full_name%></h1>
<table>
  <thead>
    <tr>
      <th>Post name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_name %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
       <!--  <td><%#= link_to 'Edit', edit_post_path(post) %></td>
        <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> |
<%= link_to 'Home', home_index_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%#= notice %></p>

<p>
  <strong>Post name:</strong>
  <%= @post.post_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%#= link_to 'Edit', edit_post_path(@post) %> 
<%= link_to 'Back', posts_path %>
|
<%= link_to 'Home', home_index_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>